name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Spécifiez la version de .NET que vous utilisez
    - name: Build WinForms Project
      run: dotnet build barter/barter.csproj -c Release

    - name: Build Setup Wizard Project
      run: msbuild barter-setup/barter-setup.vdproj /p:Configuration=Release

    - name: Find setup.exe
      id: find_setup
      run: |
        # Rechercher le fichier setup.exe généré
        SETUP_PATH=$(find . -type f -name 'setup.exe')
        echo "SETUP_PATH=$SETUP_PATH" >> $GITHUB_ENV
    
    - name: Upload setup.exe
      uses: actions/upload-artifact@v3
      with:
        name: setup.exe
        path: ${{ env.SETUP_PATH }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download setup.exe
      uses: actions/download-artifact@v3
      with:
        name: setup.exe
        path: .

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: |
          Release for commit ${{ github.sha }}
        draft: false
        prerelease: false
        files: setup.exe
